#!/bin/bash
###############################################################################
# Patch: Set UI Settings at Build-Time
#
# In Stirling PDF V2, appName and homeDescription are stored in the database
# and configured via Admin UI. This patch pre-configures these settings
# via custom_settings.yml which is merged with settings.yml on startup.
#
# Stirling PDF reads settings in this order:
#   1. settings.yml (base, gets overwritten on updates)
#   2. custom_settings.yml (custom overrides, preserved on updates)
#   3. Environment variables (highest priority)
#
# We use custom_settings.yml because settings.yml is regenerated from template
# on startup, but custom_settings.yml is preserved.
###############################################################################

echo "Patching UI settings for build-time branding..."

# Load branding configuration
BRANDING_DIR="${BRANDING_DIR:-/tmp/branding}"
# CONFIGS_DIR can be set to /branding-template/configs for build-time (volume-safe)
CONFIGS_DIR="${CONFIGS_DIR:-/configs}"

# Default values
APP_NAME="PDF Toolbox [BAUER GROUP]"
APP_DESCRIPTION="Comprehensive PDF processing and conversion tools"
COMPANY_NAME="BAUER GROUP"

# Try to load from branding.env
if [[ -f "$BRANDING_DIR/branding.env" ]]; then
    source "$BRANDING_DIR/branding.env" 2>/dev/null || true
    APP_NAME="${BRAND_APP_NAME:-$APP_NAME}"
    APP_DESCRIPTION="${BRAND_APP_DESCRIPTION:-$APP_DESCRIPTION}"
    COMPANY_NAME="${BRAND_COMPANY_NAME:-$COMPANY_NAME}"
fi

# Create configs directory if needed
mkdir -p "$CONFIGS_DIR"

# Create custom_settings.yml (this is preserved on updates)
CUSTOM_SETTINGS_FILE="$CONFIGS_DIR/custom_settings.yml"

cat > "$CUSTOM_SETTINGS_FILE" << EOF
# =============================================================================
# Stirling PDF Custom Settings (Auto-generated by PDF Toolbox build)
# =============================================================================
# These settings override defaults in settings.yml
# This file is preserved during updates (unlike settings.yml)
#
# Full settings reference: https://docs.stirlingpdf.com/Configuration/
# =============================================================================

ui:
  appName: "${APP_NAME}"
  homeDescription: "${APP_DESCRIPTION}"
  appNameNavbar: "${APP_NAME}"
  logoStyle: "modern"
  showSocialIcons: false

system:
  defaultLocale: "en-GB"
  googleVisibility: false
  showUpdate: false
  showUpdateOnlyAdmin: true
  enableAnalytics: false
  customHTMLFiles: false
  serverCertificate:
    enabled: false
    organizationName: "${COMPANY_NAME}"

security:
  enableLogin: true
  csrfDisabled: false

EOF

echo "  Created custom_settings.yml with:"
echo "    appName: $APP_NAME"
echo "    homeDescription: $APP_DESCRIPTION"
echo "    showSocialIcons: false"

# Set permissions
chmod 644 "$CUSTOM_SETTINGS_FILE"

echo "Successfully patched UI settings via custom_settings.yml"
